services:
  atcoder:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: atcoder
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - ./config:/root/.config/atcoder-cli-nodejs